on: push
jobs:
  test:
    name: Test UP config
    runs-on:  macos-latest # macOS Catalina 10.15
    steps:
      - name: Virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: Install and Run UP
        run: |
          # Setup Test env
          defaults write -g AppleLanguages '("en-GB")';
          export TERM=xterm-256color;
          export UP_ENV="development";
          export GIT_USERNAME="foo"
          export GIT_EMAIL="foo@baz.gizmo"

          # Install
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/juliantellez/up/${GITHUB_SHA}/install.sh) $GITHUB_SHA"
