on: push
jobs:
  test:
    name: test
    runs-on:  macos-latest # macOS Catalina 10.15
    steps:
      - name: Virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: Create workspace
        run: |
          mkdir -p ~/.up; cd ~/.up;
      - name: Fetch
        run: |
          curl -L "https://github.com/juliantellez/up/tarball/${GITHUB_SHA}" | tar -xzv --strip-components 1 &> /dev/null;
      - name: sh main
        run: |
          export TERM=xterm-256color;
          . $(pwd)/main.sh;
          steps
