on: push
jobs:
  test:
    name: test
    runs-on:  macos-latest # macOS Catalina 10.15
    steps:
      - name: virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: create workspace
        run: |
          mkdir -p ~/.up; cd ~/.up;
      - name: fetch
        run: |
          curl -L https://github.com/juliantellez/up/tarball/master | tar -xzv --strip-components 1 &> /dev/null;
      - name: list
        run: |
          ls
