on: push
jobs:
  test:
    name: test
    runs-on:  macos-latest # macOS Catalina 10.15
    steps:
      - name: virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: checkout
        run: |
          mkdir -p ~/.up; cd ~/.up; \
          curl -L https://github.com/juliantellez/up/tarball/master | tar -xzv --strip-components 1 &> /dev/null; \
          ls

