on: push
jobs:
  test:
    name: Test UP installation
    runs-on:  macos-latest # macOS Catalina 10.15
    steps:
      - name: Virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: Create workspace
        run: |
          mkdir -p ~/.up; cd ~/.up;
      - name: Fetch Commit
        run: |
          curl -L "https://github.com/juliantellez/up/tarball/${GITHUB_SHA}" | tar -xzv --strip-components 1 &> /dev/null;
      - name: Run steps
        run: |
          # Setup Test env
          defaults write -g AppleLanguages '("en-GB")';
          export TERM=xterm-256color;
          export UP_ENV="development";

          . $(pwd)/main.sh;
          steps;
